#
#                                             ▄▄
#       ▀███▀▀▀██▄                          ▀███                           ▀███▀▀▀██▄ ███▀▀██▀▀██████▀▀▀██▄
#         ██   ▀██▄                           ██                             ██   ▀██▄█▀   ██   ▀█ ██   ▀██▄
# ▄██▀███ ██   ▄██  ▄█▀██▄ ▀████████▄    ▄█▀▀███   ▄██▀██▄▀████████▄█████▄   ██   ▄██      ██      ██   ▄██
# ██   ▀▀ ███████  ██   ██   ██    ██  ▄██    ██  ██▀   ▀██ ██    ██    ██   ███████       ██      ███████
# ▀█████▄ ██  ██▄   ▄█████   ██    ██  ███    ██  ██     ██ ██    ██    ██   ██  ██▄       ██      ██
# █▄   ██ ██   ▀██▄██   ██   ██    ██  ▀██    ██  ██▄   ▄██ ██    ██    ██   ██   ▀██▄     ██      ██
# ██████▀████▄ ▄███▄████▀██▄████  ████▄ ▀████▀███▄ ▀█████▀▄████  ████  ████▄████▄ ▄███▄  ▄████▄  ▄████▄
#
#
# Text created on the website - https://texteditor.com/multiline-text-art/
#
# Placeholders:
# %sRandomRTP_rtp_count% - counts how many people have been teleported. Teleportations are counted after successful teleportation by /rtp, /rtp near, /rtp world.
#
# Permissions:
#
#
# (sRandomRtp.Cooldown.N - replace “N” with your time. With this permission you can set a custom cooldown on the /rtp command.
# If the permission is not set, the cooldown for the command is taken from the config. If cooldown on the command is disabled, the permission will not work.);
# (sRandomRTP.Command.bypass - bypass the cooldown for commands and teleportation.);
# (sRandomRTP.Command.Rtp - allow using the /rtp command.);
# (sRandomRTP.Command.Reload - allow using the /rtp reload command.);
# (sRandomRTP.Command.Near - allow using the /rtp near command.);
# (sRandomRTP.Command.Version - allow the /rtp version command to be used.);
# (sRandomRTP.Command.Help - allow the use of the /rtp help command.);
# (sRandomRTP.Command.World - allow the use of the /rtp world command.);
# (sRandomRTP.Command.Cancel - allow cancelling rtp with the command - /rtp cancel.);
# (sRandomRTP.Command.Back - allows you to use the command - /rtp back.);
# (sRandomRTP.Command.Base - allows you to use the command - /rtp base.);
# (sRandomRTP.Cooldown.Chunky - allows you to use the command - /rtp chunky.);
# (sRandomRTP.Command.Player - allows to use the command - /rtp player.);
# (sRandomRTP.Command.Deny - allows the use of the /rtp deny command (this command works exclusively with the /rtp player command!).
# (sRandomRTP.Command.Accept - allows the use of the /rtp accept command (this command works exclusively with the /rtp player command!).
#
#

# debug to the console, which are displayed when using the /rtp command
logs: false
# Determines whether to enable automatic notifications about new plugin versions for players.
Auto-Checking-New-Version-Players-Enabled: true
# Determines whether to enable automatic notifications about new plugin versions for the console.
Auto-Checking-New-Version-Console-Enabled: true
# Frequency of checking for new plugin versions (in seconds) (1800 seconds = 30 minutes)
Period-Checking-New-Version: 1800
# Default language for the plugin, English by default.
# This file custom_messages is created to be translated into any language you want
# de - Deutsch (German) || en - English (United States) || es - Español (Spanish) || fr - Français (French) || it - Italiano (Italian) ||
# ja - 日本語 (Japanese) || ko - 한국어 (Korean) || pl - Polski (Polish) || pt - Português (Brazilian Portuguese) || ru - Русский (Russian) ||
# ua - Українська (Ukrainian) || vi - Tiếng Việt (Vietnamese) || zh - 中文 (Simplified Chinese) || ar - العربية (Arabic)
Language: en