name: sRandomRTP
version: 3.0
main: org.sRandomRTP.Main
api-version: 1.16
folia-supported: true
depend:
  - LuckPerms
softdepend:
  - WorldGuard
  - WorldEdit
  - Vault
  - PlaceholderAPI
  - Chunky
authors: [snezhok69_, Snon_S]
commands:
  rtp: {}