name: sRandomRTP
version: 3.0
main: org.sRandomRTP.Main
api-version: 1.13
softdepend:
  - WorldGuard
  - LuckPerms
  - WordEdit
  - Vault
  - PlaceholderAPI
authors: [snezhok69_, Snon_S]
commands:
  rtp: {}